name: app_dependences
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.2.1
  flutter_modular: ^4.4.1
  flutter_triple: ^1.2.6
  flutter_mobx: ^2.0.4
  mobx_triple: ^1.1.3+1
  mobx: ^2.0.6+1
  shared_preferences: ^2.0.13
  permission_handler: ^9.1.0
  dartz: ^0.10.1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
