name: dev_dependences
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ">=0.2.0 < 1.0.0"
  triple_test: ">=1.0.0 < 2.0.0"
  flutter_modular_test: ">=1.0.4 < 2.0.0"

flutter:
