import 'package:flutter_modular/flutter_modular.dart';
import 'package:xp_ob/app/modules/home_module/presenter/home_page.dart';

class HomeModule extends Module {
  @override
  List<Bind> get binds => [
        // ...featureDI, // feature binder generated by difeat
      ];

  @override
  List<ModularRoute> get routes => [
        ChildRoute(Modular.initialRoute, child: (_, args) => const HomePage()),
      ];
}
