import 'package:flutter_modular/flutter_modular.dart';

import 'presenter/pix_page.dart';

class PixModule extends Module {
  @override
  List<Bind> get binds => [
        // ...featureDI, // feature binder generated by difeat
      ];

  @override
  List<ModularRoute> get routes => [
        ChildRoute(
          Modular.initialRoute,
          child: (_, args) => const PixPage(),
        ),
      ];
}
